#!/usr/bin/env python3
"""
dev-assets-tidy: review and groom existing memory entries.

Setup turns lazy-init lumps into structured files (no order → ordered).
Tidy is the second pass that runs periodically: structured files drift
over time (stale items, duplicates, mistakes), and tidy lets the user
review every entry, mark keep/delete/edit, and write the result back.

Workflow:
  1. `prepare` — scan the target scope (branch + optional repo), parse
     each .md file into top-level bullet entries, optionally inject
     agent hints (STALE/DUP/OK/UNCLEAR + reason), render a static
     review.html the user opens locally and exports a plan.json from.
  2. `apply` — read the user's plan.json, snapshot the current scope
     into tidy_backup_<ts>/, then rewrite each file according to the
     keep/delete/edit actions per entry.

Skipped on purpose:
  - Auto-sync blocks (between AUTO-GENERATED-START/END) are never
    surfaced — they're regenerated by other commands.
  - Manifest.json is not a tidy target; it's structured data, not prose.
"""

import argparse
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from dev_asset_common import (
    AUTO_END,
    AUTO_START,
    ensure_branch_paths_exist,
    join_sections,
    split_sections,
)

HTML_TEMPLATE_PATH = Path(__file__).resolve().parent / "assets" / "tidy_review.html"

# Files we tidy. Keys map to dev_asset_common.asset_paths() entries.
BRANCH_FILE_KEYS = (
    "overview",
    "decisions",
    "progress",
    "risks",
    "glossary",
    "unsorted",
    "pending_promotion",
)
REPO_FILE_KEYS = (
    "repo_overview",
    "repo_decisions",
    "repo_glossary",
)

VALID_HINTS = {"STALE", "DUP", "OK", "UNCLEAR"}
VALID_ACTIONS = {"keep", "delete", "edit"}


def _now_stamp():
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def _strip_auto_block(body):
    """Remove the AUTO-GENERATED block from a section body so tidy
    doesn't show machine-managed state to the user. Returns the body
    with the block (and surrounding blank lines) removed."""
    if AUTO_START not in body or AUTO_END not in body:
        return body
    start = body.index(AUTO_START)
    end = body.index(AUTO_END) + len(AUTO_END)
    return (body[:start].rstrip() + "\n" + body[end:].lstrip()).strip()


def _parse_entries(body):
    """Split a section body into top-level bullet entries. A continuation
    line (indented or non-bullet) is appended to the previous entry. Returns
    a list of {entry_idx, text} dicts. Entries that match placeholder
    markers (待补充 etc.) are returned with `is_placeholder=True` so the
    UI can render them faded but still allow delete/edit."""
    entries = []
    current = None
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped:
            if current is not None:
                entries.append(current)
                current = None
            continue
        if stripped.startswith("- "):
            if current is not None:
                entries.append(current)
            current = {"text": stripped[2:].strip(), "raw_lines": [line]}
        elif current is not None:
            # Continuation: keep the original indentation when reconstructing.
            current["text"] = current["text"] + "\n" + stripped
            current["raw_lines"].append(line)
        # Lines before any bullet (free-form prose) are ignored — tidy
        # only operates on bullet-style entries to keep the action set
        # finite. Free-form prose stays untouched in the file.
    if current is not None:
        entries.append(current)
    indexed = []
    for idx, ent in enumerate(entries):
        text = ent["text"].strip()
        is_placeholder = text in ("待补充", "待刷新")
        indexed.append({
            "entry_idx": idx,
            "text": text,
            "is_placeholder": is_placeholder,
        })
    return indexed


def _file_label(file_key):
    if file_key.startswith("repo_"):
        return f"repo/{file_key[5:]}.md"
    return f"branch/{file_key}.md"


def _scope_paths(paths, include_repo):
    """Return ordered (file_key, path) tuples that exist."""
    out = []
    for key in BRANCH_FILE_KEYS:
        p = paths.get(key)
        if p and p.exists():
            out.append((key, p))
    if include_repo:
        for key in REPO_FILE_KEYS:
            p = paths.get(key)
            if p and p.exists():
                out.append((key, p))
    return out


def _scan_scope(paths, include_repo):
    """Scan target files into a tree of {file, sections, entries}."""
    files = []
    for file_key, path in _scope_paths(paths, include_repo):
        content = path.read_text(encoding="utf-8")
        prefix, sections = split_sections(content)
        section_records = []
        for section_idx, (title, body) in enumerate(sections):
            cleaned = _strip_auto_block(body)
            entries = _parse_entries(cleaned)
            if not entries:
                continue
            section_records.append({
                "section_idx": section_idx,
                "title": title,
                "entries": entries,
            })
        if not section_records:
            continue
        files.append({
            "file_key": file_key,
            "label": _file_label(file_key),
            "path": str(path),
            "sections": section_records,
        })
    return files


def _entry_id(file_key, section_idx, entry_idx):
    return f"{file_key}::{section_idx}::{entry_idx}"


def _flatten_entries(files):
    """Yield every entry with its stable ID for hint/plan lookup."""
    for f in files:
        for s in f["sections"]:
            for e in s["entries"]:
                yield _entry_id(f["file_key"], s["section_idx"], e["entry_idx"]), f, s, e


def _validate_hints(hints):
    """Ensure each value is {label: ..., reason: ...} with valid label."""
    if hints is None:
        return {}
    if not isinstance(hints, dict):
        raise ValueError("hints must be a JSON object keyed by entry id")
    cleaned = {}
    for k, v in hints.items():
        if not isinstance(v, dict):
            raise ValueError(f"hint for {k} must be an object")
        label = (v.get("label") or "").strip().upper()
        reason = (v.get("reason") or "").strip()
        if label and label not in VALID_HINTS:
            raise ValueError(f"hint label for {k} must be one of {sorted(VALID_HINTS)}")
        cleaned[k] = {"label": label, "reason": reason}
    return cleaned


def _render_html(files, hints, scope_meta, output_path):
    """Inject scan + hints into the HTML template and write to disk."""
    template = HTML_TEMPLATE_PATH.read_text(encoding="utf-8")
    payload = {
        "scope": scope_meta,
        "files": files,
        "hints": hints,
    }
    payload_json = json.dumps(payload, ensure_ascii=False, indent=2)
    rendered = template.replace("__TIDY_DATA_PLACEHOLDER__", payload_json)
    rendered = rendered.replace("__SCOPE_LABEL_PLACEHOLDER__",
                                f"{scope_meta['repo_key']} · {scope_meta['branch']}")
    output_path.write_text(rendered, encoding="utf-8")


def command_prepare(args):
    repo_root, branch_name, branch_key, storage_root, repo_key, repo_dir, branch_dir, paths = ensure_branch_paths_exist(
        args.repo, args.context_dir, args.branch
    )
    include_repo = args.scope == "branch+repo"
    files = _scan_scope(paths, include_repo)

    hints = {}
    if args.hints_json:
        hints = _validate_hints(json.loads(args.hints_json))
    elif args.hints_file:
        hints = _validate_hints(json.loads(Path(args.hints_file).read_text(encoding="utf-8")))

    scope_meta = {
        "repo_root": str(repo_root),
        "repo_key": repo_key,
        "branch": branch_name,
        "branch_dir": str(branch_dir),
        "include_repo": include_repo,
        "generated_at": _now_stamp(),
    }

    review_dir = branch_dir / "tidy_review"
    review_dir.mkdir(parents=True, exist_ok=True)
    out_path = review_dir / f"review_{scope_meta['generated_at']}.html"
    _render_html(files, hints, scope_meta, out_path)

    entry_index = []
    for entry_id, f, s, e in _flatten_entries(files):
        entry_index.append({
            "id": entry_id,
            "file": f["label"],
            "section": s["title"],
            "text": e["text"],
            "is_placeholder": e["is_placeholder"],
        })

    print(json.dumps({
        "mode": "prepare",
        "review_html": str(out_path),
        "open_url": f"file://{out_path}",
        "scope": scope_meta,
        "entry_count": len(entry_index),
        "entries": entry_index,
        "next_steps": [
            "1) Read the entries above; for each ID assign a hint (STALE/DUP/OK/UNCLEAR + short reason).",
            "2) Re-run prepare with --hints-json '{\"<id>\":{\"label\":\"STALE\",\"reason\":\"...\"}, ...}' to bake hints into the HTML.",
            "3) Tell the user to open the printed open_url in a browser, mark keep/delete/edit per entry, then click Export Plan.",
            "4) When the user signals they downloaded plan.json, run: dev_asset_tidy.py apply --plan-file <path>.",
        ],
    }, ensure_ascii=False, indent=2))
    return 0


def _backup_scope(branch_dir, paths, include_repo, stamp):
    """Snapshot every file we may touch into tidy_backup_<stamp>/. Files
    are stored under the same relative key naming used internally so
    apply can self-document what was preserved."""
    backup_dir = branch_dir / f"tidy_backup_{stamp}"
    backup_dir.mkdir(parents=True, exist_ok=True)
    saved = []
    for file_key, path in _scope_paths(paths, include_repo):
        dest = backup_dir / f"{file_key}.md"
        shutil.copy2(path, dest)
        saved.append({"file_key": file_key, "src": str(path), "backup": str(dest)})
    (backup_dir / "manifest.json").write_text(
        json.dumps({"saved_at": stamp, "files": saved}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return backup_dir, saved


def _apply_actions_to_section(body, entry_actions):
    """Rewrite a section body so each entry is either kept, removed,
    or replaced by its `new_text`. entry_actions is keyed by entry_idx.
    Lines outside top-level bullets pass through unchanged."""
    lines = body.splitlines()
    out_blocks = []
    current_block = []
    current_idx = -1

    def flush():
        nonlocal current_block, current_idx
        if not current_block:
            return
        action = entry_actions.get(current_idx, {"action": "keep"})
        kind = action.get("action", "keep")
        if kind == "delete":
            pass
        elif kind == "edit":
            new_text = (action.get("new_text") or "").strip()
            if new_text:
                # Render edited text as a fresh bullet, splitting on
                # newlines so multi-line edits stay a single entry with
                # continuation lines indented to depth 2.
                first, *rest = new_text.split("\n")
                out_blocks.append("- " + first.strip())
                for cont in rest:
                    out_blocks.append("  " + cont.strip())
        else:
            out_blocks.extend(current_block)
        current_block = []
        current_idx = -1

    entry_seen = -1
    for raw in lines:
        stripped = raw.strip()
        if stripped.startswith("- "):
            flush()
            entry_seen += 1
            current_idx = entry_seen
            current_block = [raw]
        elif current_block and stripped and (raw.startswith("  ") or raw.startswith("\t")):
            current_block.append(raw)
        elif not stripped:
            flush()
            out_blocks.append(raw)
        else:
            # Free-form prose between bullets — leave alone.
            flush()
            out_blocks.append(raw)
    flush()

    # Trim trailing blank lines for a tidy file.
    while out_blocks and not out_blocks[-1].strip():
        out_blocks.pop()
    rebuilt = "\n".join(out_blocks).strip()
    if not rebuilt:
        # Section emptied out entirely — leave the placeholder so the
        # file remains valid and capture's _section_is_placeholder_only
        # logic can still detect it.
        return "- 待补充"
    return rebuilt


def _rewrite_file(path, plan_actions_by_section):
    """For a single file, apply per-section per-entry actions then
    rewrite the file. Auto-sync blocks pass through untouched."""
    content = path.read_text(encoding="utf-8")
    prefix, sections = split_sections(content)
    new_sections = []
    for section_idx, (title, body) in enumerate(sections):
        actions = plan_actions_by_section.get(section_idx)
        if not actions:
            new_sections.append((title, body))
            continue
        # Preserve auto-sync block: split body at AUTO_START, only tidy
        # the part before; auto-block goes back as-is.
        if AUTO_START in body and AUTO_END in body:
            head_end = body.index(AUTO_START)
            head = body[:head_end].rstrip()
            tail = body[head_end:]
            new_head = _apply_actions_to_section(head, actions)
            new_body = (new_head + "\n\n" + tail).strip()
        else:
            new_body = _apply_actions_to_section(body, actions)
        new_sections.append((title, new_body))
    path.write_text(join_sections(prefix, new_sections), encoding="utf-8")


def command_apply(args):
    repo_root, branch_name, branch_key, storage_root, repo_key, repo_dir, branch_dir, paths = ensure_branch_paths_exist(
        args.repo, args.context_dir, args.branch
    )

    plan = json.loads(Path(args.plan_file).read_text(encoding="utf-8"))
    actions = plan.get("actions") or []
    include_repo = (plan.get("scope") or {}).get("include_repo", False)

    # Group actions by file/section for efficient rewrite.
    grouped = {}  # file_key -> section_idx -> entry_idx -> action
    invalid = []
    for item in actions:
        eid = item.get("id") or ""
        kind = (item.get("action") or "").strip().lower()
        if kind not in VALID_ACTIONS:
            invalid.append({"id": eid, "reason": f"unknown action {kind!r}"})
            continue
        try:
            file_key, section_idx_str, entry_idx_str = eid.split("::")
            section_idx = int(section_idx_str)
            entry_idx = int(entry_idx_str)
        except (ValueError, AttributeError):
            invalid.append({"id": eid, "reason": "malformed id"})
            continue
        if file_key not in paths and not (file_key.startswith("repo_") and file_key in paths):
            invalid.append({"id": eid, "reason": f"unknown file_key {file_key!r}"})
            continue
        grouped.setdefault(file_key, {}).setdefault(section_idx, {})[entry_idx] = {
            "action": kind,
            "new_text": item.get("new_text"),
        }

    stamp = _now_stamp()
    backup_dir, _ = _backup_scope(branch_dir, paths, include_repo, stamp)

    rewritten = []
    for file_key, sec_actions in grouped.items():
        path = paths.get(file_key)
        if not path or not path.exists():
            invalid.append({"file_key": file_key, "reason": "file missing at apply time"})
            continue
        _rewrite_file(path, sec_actions)
        rewritten.append({"file_key": file_key, "path": str(path)})

    summary_path = branch_dir / "tidy_review" / f"summary_{stamp}.md"
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    summary_lines = [
        f"# Tidy summary {stamp}",
        "",
        f"- branch: `{branch_name}`",
        f"- include_repo: `{include_repo}`",
        f"- backup: `{backup_dir}`",
        f"- actions submitted: {len(actions)}",
        f"- files rewritten: {len(rewritten)}",
        f"- invalid items: {len(invalid)}",
    ]
    if plan.get("notes"):
        summary_lines += ["", "## notes", "", plan["notes"]]
    if invalid:
        summary_lines += ["", "## invalid", ""]
        summary_lines += [f"- {json.dumps(v, ensure_ascii=False)}" for v in invalid]
    summary_path.write_text("\n".join(summary_lines) + "\n", encoding="utf-8")

    print(json.dumps({
        "mode": "apply",
        "branch": branch_name,
        "branch_dir": str(branch_dir),
        "backup_dir": str(backup_dir),
        "rewritten": rewritten,
        "invalid": invalid,
        "summary": str(summary_path),
        "actions_count": len(actions),
    }, ensure_ascii=False, indent=2))
    return 0


def _add_common_args(p):
    p.add_argument("--repo", default=".", help="Path inside the target Git repository")
    p.add_argument("--context-dir", help="User-home storage root. Defaults to ~/.dev-assets/repos")
    p.add_argument("--branch", help="Branch name. Defaults to the current checked-out branch")


def main():
    parser = argparse.ArgumentParser(description="Review and tidy existing dev-assets memory entries.")
    sub = parser.add_subparsers(dest="command", required=True)

    p_prep = sub.add_parser("prepare", help="Scan scope, render review.html (optionally with agent hints)")
    _add_common_args(p_prep)
    p_prep.add_argument("--scope", choices=("branch", "branch+repo"), default="branch")
    hint_group = p_prep.add_mutually_exclusive_group()
    hint_group.add_argument("--hints-json", help="Inline JSON object keyed by entry id with {label, reason}")
    hint_group.add_argument("--hints-file", help="Path to JSON file with the same shape as --hints-json")

    p_apply = sub.add_parser("apply", help="Apply a downloaded plan.json (with backup snapshot)")
    _add_common_args(p_apply)
    p_apply.add_argument("--plan-file", required=True)

    args = parser.parse_args()
    try:
        return {
            "prepare": command_prepare,
            "apply": command_apply,
        }[args.command](args)
    except Exception as exc:
        print(json.dumps({"error": str(exc)}, ensure_ascii=False), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
